FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

MAINTAINER Your Name "berlinguyinca@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python3-pip git

# always good to update pip
RUN pip3 install --upgrade pip

